# Site settings -----------------------------------
title: Guide du consom'acteur - Epinal
email: guide-consomacteur@epinal-en-transition.fr
description: Le guide du consom’acteur a pour ambition de favoriser les démarches de type circuits courts, bio, agroécologie, recyclage ou encore réparation, autour d'Epinal.
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
# url: "https://clairezed.github.io" # the base hostname & protocol for your site
url: "https://guide-consomacteur-epinal.netlify.com" # the base hostname & protocol for your site


# Social settings ------------------------------------
# github_username: clairezed
# twitter_username: ZooletteDesBois

# Build settings --------------------------------------
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
